src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=83)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Url(
     *    message = "l'url saisie n'est pas une url valide, http ou https demandés.",
     *    protocols = {"http", "https"},
     * )
     */
    private $illustration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Component\Mime\Address;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre'
                ])
            ->add('content', TextareaType::class, [
                'label' => 'Contenu'
                ])
            ->add('illustration', TextType::class, [
                'label' => 'Image',
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Form\NewsType;
use App\Repository\NewsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\Exception\AccessDeniedException;

class NewsController extends AbstractController
{
    /**
     * @Route("/news", name="news")
     */
    public function index(NewsRepository $repo)
    {
        return $this->render('news/index.html.twig', [
            'news' => $repo->findAll(),
        ]);
    }

    /**
     * @Route("/news/{id<[0-9]+>}", name="show_news")
     */
    public function showNews(News $news)
    {
        return $this->render('news/showNews.html.twig', [
            'news' => $news,
        ]);
    }

    /**
     * Undocumented function
     * 
     * IsGranted("ROLE_ADMIN")
     * @Route("/admin/news/ajouter", name="add_news")
     * @Route("/admin/news/{id<[0-9]+>}/editer", name="edit_news")
     *
     * @param News $news
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return void
     */
    public function addNews(News $news = null, Request $request, EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if (!$news) {
            $news = new News();
        }

        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $news->setCreatedAt(new \DateTime());

            $em->persist($news);
            $em->flush();
            
            $this->addFlash('success', 'La nouvelle '.$news->getTitle().' est en ligne !');
            return $this->redirectToRoute('show_news', ['id' => $news->getId()]);
        }
        

        return $this->render('news/addNews.html.twig', [
            'formNews' => $form->createView(),
            'editNews' => $news->getId() !== null, 
            'news'     => $news
        ]);
    }

    /**
     * Delete a news
     * 
     * IsGranted("ROLE_ADMIN")
     * @Route("/admin/news/{id<[0-9]+>}/supprimer", name="remove_news", methods={"DELETE"})
     *
     * @param integer $id
     * @return void
     */
    public function removeNews(News $news) 
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        // try {
            $em = $this->getDoctrine()->getManager();
            $em->remove($news);
            $em->flush();
    
            $this->addFlash('success', 'La news '.$news->getTitle().' a bien été supprimée !');
            return $this->redirectToRoute('news');
        // } 
        // catch (\Throwable $th) {
            // $this->addFlash('warning', 'Un problème est survenu : '.$th->getMessage());
        // } 

    }
}

templates/news/addNews.html.twig
{% extends 'base.html.twig' %}

{% block title %}LaBroq'News !
{% endblock %}

{% block body %}
	<div class="container">

		<div class="news">

		<div class="text-center mb-3">
			<a class="btn btn-sm btn-outline-green" href="{{ path('news') }}">Retour</a>
			{% if editNews %}		
			<form method="post" action="{{ path('remove_news', {'id': news.id}) }}" 
			onsubmit="return confirm('Etes-vous sur de vouloir supprimer la news ?');">
				<input type="hidden" name="_method" value="DELETE">
				<button class="btn btn-danger btn-sm mt-2">Supprimer</button>
			</form>
			{% endif %}
		</div>
		
			<h1 class="text-center">{{ news.title }}</h1>
			
			{{ form_start(formNews, {'attr': {'onsubmit': "return confirm('Publier la publication ?');"}}) }}			
				
				{{ form_widget(formNews) }}	
				
				{% if editNews %}
					<button type="submit" class="btn btn-secondary w-100">Modifier</button>	
				{% else %}
					<button type="submit" class="btn btn-outline-secondary w-100">Publier</button>		
				{% endif %}

			{{ form_end(formNews) }}

		</div>

	</div>
{% endblock %}

{% block javascripts %}
{# <script src="/js/news.js"></script> #}
{% endblock %}

        

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LaBroq'News !
{% endblock %}

{% block body %}
	<div class="container-fluid">

		<h1 class="text-center">Toutes Les News !</h1>


		<div class="news">
		
			{% if is_granted("ROLE_ADMIN") %}
			<a class="btn btn-outline-warning btn-sm" href="{{ path('add_news') }}">Ajouter une nouvelle ?</a>
			{% endif %}

			{% for new in news %}
				<div class="news index-news border">

					<div class="img-news">
						<img src="{{ new.illustration }}" alt="image d'illustration pour l'article nomé {{ new.title }}">
					</div>

					<div class="content">
						<h2>{{ new.title | slice(0,15) }}</h2>
						<h5>{{ new.content | slice(0,60) }}...</h5>
						<p class="text-muted ft-1">{{ new.createdAt | date('d/m/Y H:i') }}</p>
						<a class="float-right btn btn-green btn-sm" href="{{ path('show_news', {'id': new.id }) }}">En Voir Plus</a>
					</div>

				</div>
			{% else %}
				<h5><em>Aucunes News pour le moment ! </em></h5>
			{% endfor %}

		</div>

	</div>
{% endblock %}

templates/news/showNews.html.twig
{% extends 'base.html.twig' %}

{% block title %}LaBroq'News - {{ news.title }}
{% endblock %}

{% block body %}
	<div class="container-fluid">

		<div class="news">

		{% if is_granted("ROLE_ADMIN") %}
			<a class="btn btn-sm btn-outline-warning" href="{{ path('edit_news', {'id': news.id}) }}">Editer la news</a>
		{% endif %}
		

			<div class="news border p-3 m-4">
				<h1 class="text-center">{{ news.title }}</h1>
				<p class="text-muted">{{ news.createdAt | date('d/m/Y H:i') }}</p>
				<div class="img-news">
					<img src="{{ news.illustration }}" alt="image d'illustration pour l'article nomé {{ news.title }}">
				</div>
				<h5 class="show-content">{{ news.content }}</h5>
			</div>

			<a class="btn btn-sm btn-outline-green" href="{{ path('news') }}">Retour</a>

		</div>


	</div>
{% endblock %}